---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  - dapper e2e-sonobuoy
  - dapper e2e-verify
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: upload-artifacts
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: push-controller
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    build_args:
    - ARCH=amd64
    - TAG=${DRONE_TAG}-amd64
    password:
      from_secret: docker_password
    repo: "rancher/system-upgrade-controller"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: push-e2e-tests
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    build_args:
    - ARCH=amd64
    - TAG=${DRONE_TAG}-amd64
    target: e2e-tests
    password:
      from_secret: docker_password
    repo: "rancher/system-upgrade-controller"
    tag: "${DRONE_TAG}-amd64-e2e-tests"
    username:
      from_secret: docker_username
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*
    event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: upload-artifacts
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: push-controller
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    build_args:
    - ARCH=arm64
    - TAG=${DRONE_TAG}-arm64
    password:
      from_secret: docker_password
    repo: "rancher/system-upgrade-controller"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: push-e2e-tests
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    build_args:
    - ARCH=arm64
    - TAG=${DRONE_TAG}-arm64
    target: e2e-tests
    password:
      from_secret: docker_password
    repo: "rancher/system-upgrade-controller"
    tag: "${DRONE_TAG}-arm64-e2e-tests"
    username:
      from_secret: docker_username
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*
    event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: upload-artifacts
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: push-controller
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    build_args:
    - ARCH=arm
    - TAG=${DRONE_TAG}-arm
    password:
      from_secret: docker_password
    repo: "rancher/system-upgrade-controller"
    tag: "${DRONE_TAG}-arm"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: controller
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    target: "rancher/system-upgrade-controller:${DRONE_TAG}"
    template: "rancher/system-upgrade-controller:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: e2e-tests
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "rancher/system-upgrade-controller:${DRONE_TAG}-e2e-tests"
    template: "rancher/system-upgrade-controller:${DRONE_TAG}-ARCH-e2e-tests"
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*
    event:
      - tag

depends_on:
- amd64
- arm64
- arm
