apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
- manifests/clusterrole.yaml
- manifests/clusterrolebinding.yaml
- manifests/system-upgrade-controller.yaml
