#!/usr/bin/env bash

set -e

cd $(dirname $0)/..

./scripts/cluster-down > /dev/null 2>&1 || true
./scripts/cluster-prepare
docker-compose up \
  --build \
  --detach \
  --force-recreate \
  --quiet-pull \
  --renew-anon-volumes
