apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.upgrade.cattle.io
spec:
  group: upgrade.cattle.io
  names:
    categories:
    - upgrade
    kind: Plan
    plural: plans
    singular: plan
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.upgrade.image
      name: Image
      type: string
    - jsonPath: .spec.channel
      name: Channel
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              channel:
                nullable: true
                type: string
              concurrency:
                type: integer
              cordon:
                type: boolean
              drain:
                nullable: true
                properties:
                  deleteEmptydirData:
                    nullable: true
                    type: boolean
                  deleteLocalData:
                    nullable: true
                    type: boolean
                  disableEviction:
                    type: boolean
                  force:
                    type: boolean
                  gracePeriod:
                    nullable: true
                    type: integer
                  ignoreDaemonSets:
                    nullable: true
                    type: boolean
                  podSelector:
                    nullable: true
                    properties:
                      matchExpressions:
                        items:
                          properties:
                            key:
                              nullable: true
                              type: string
                            operator:
                              nullable: true
                              type: string
                            values:
                              items:
                                nullable: true
                                type: string
                              nullable: true
                              type: array
                          type: object
                        nullable: true
                        type: array
                      matchLabels:
                        additionalProperties:
                          nullable: true
                          type: string
                        nullable: true
                        type: object
                    type: object
                  skipWaitForDeleteTimeout:
                    type: integer
                  timeout:
                    nullable: true
                    type: integer
                type: object
              nodeSelector:
                nullable: true
                properties:
                  matchExpressions:
                    items:
                      properties:
                        key:
                          nullable: true
                          type: string
                        operator:
                          nullable: true
                          type: string
                        values:
                          items:
                            nullable: true
                            type: string
                          nullable: true
                          type: array
                      type: object
                    nullable: true
                    type: array
                  matchLabels:
                    additionalProperties:
                      nullable: true
                      type: string
                    nullable: true
                    type: object
                type: object
              prepare:
                nullable: true
                properties:
                  args:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  command:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  envFrom:
                    items:
                      properties:
                        configMapRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                        prefix:
                          nullable: true
                          type: string
                        secretRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                      type: object
                    nullable: true
                    type: array
                  envs:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                        valueFrom:
                          nullable: true
                          properties:
                            configMapKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                            fieldRef:
                              nullable: true
                              properties:
                                apiVersion:
                                  nullable: true
                                  type: string
                                fieldPath:
                                  nullable: true
                                  type: string
                              type: object
                            resourceFieldRef:
                              nullable: true
                              properties:
                                containerName:
                                  nullable: true
                                  type: string
                                divisor:
                                  nullable: true
                                  type: string
                                resource:
                                  nullable: true
                                  type: string
                              type: object
                            secretKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                          type: object
                      type: object
                    nullable: true
                    type: array
                  image:
                    nullable: true
                    type: string
                  volumes:
                    items:
                      properties:
                        destination:
                          nullable: true
                          type: string
                        name:
                          nullable: true
                          type: string
                        source:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                type: object
              secrets:
                items:
                  properties:
                    name:
                      nullable: true
                      type: string
                    path:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              serviceAccountName:
                nullable: true
                type: string
              tolerations:
                items:
                  properties:
                    effect:
                      nullable: true
                      type: string
                    key:
                      nullable: true
                      type: string
                    operator:
                      nullable: true
                      type: string
                    tolerationSeconds:
                      nullable: true
                      type: integer
                    value:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              upgrade:
                nullable: true
                properties:
                  args:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  command:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  envFrom:
                    items:
                      properties:
                        configMapRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                        prefix:
                          nullable: true
                          type: string
                        secretRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                      type: object
                    nullable: true
                    type: array
                  envs:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                        valueFrom:
                          nullable: true
                          properties:
                            configMapKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                            fieldRef:
                              nullable: true
                              properties:
                                apiVersion:
                                  nullable: true
                                  type: string
                                fieldPath:
                                  nullable: true
                                  type: string
                              type: object
                            resourceFieldRef:
                              nullable: true
                              properties:
                                containerName:
                                  nullable: true
                                  type: string
                                divisor:
                                  nullable: true
                                  type: string
                                resource:
                                  nullable: true
                                  type: string
                              type: object
                            secretKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                          type: object
                      type: object
                    nullable: true
                    type: array
                  image:
                    nullable: true
                    type: string
                  volumes:
                    items:
                      properties:
                        destination:
                          nullable: true
                          type: string
                        name:
                          nullable: true
                          type: string
                        source:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                type: object
              version:
                nullable: true
                type: string
            required:
            - upgrade
            type: object
          status:
            properties:
              applying:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              latestHash:
                nullable: true
                type: string
              latestVersion:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
