volumes:
  kubeconfig:
    name: e2e-local-kubeconfig

services:

  server:
    container_name: k3s-server-1
    image: "e2e/cluster/local/k3s"
    build:
      context: ./images/k3s/.
      args:
        - ARCH=${ARCH}
    command: server --disable=traefik,metrics-server --disable-helm-controller --tls-san 172.17.0.1
    environment:
      - K3S_TOKEN=e2e
    hostname: k3s-server-1
    privileged: true
    ports:
      - "6443:6443" # k3s
    volumes:
      - source: kubeconfig
        target: /etc/rancher/k3s
        type: volume

  agent:
    depends_on:
      - server
    container_name: k3s-agent-1
    image: "e2e/cluster/local/k3s"
    command: agent --server https://k3s-server-1:6443
    environment:
      - K3S_TOKEN=e2e
    hostname: k3s-agent-1
    privileged: true
