#!/bin/bash
set -e

if [ "${ARCH}" != "amd64" ]; then
    exit 0
fi

if [ ! -f ./bin/terraform-controller ]; then
    $(dirname $0)/build-controller
fi

cd $(dirname $0)/..

k3s server&
k3s_pid=$!

kubeconfig=/etc/rancher/k3s/k3s.yaml
declare -i i; i=0
until [ -f $kubeconfig ]; do
    echo "sleeping while waiting for k3s to start..."
    if (( i > 15 )); then
        break
    fi

    sleep 2
    i+=1
done

export KUBECONFIG=$kubeconfig
export NAMESPACE=terraform-controller

./bin/terraform-controller --threads 1&
tfc_pid=$!

sleep 2 #slight pause to make sure everything is running

echo "Starting e2e Testing"
go test -json -count=1 ./e2e/...
