#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}
KUBERNETES_RELEASE=v1.17.0

IMAGE=${REPO}/kubectl:${KUBERNETES_RELEASE}
docker build -t ${IMAGE} --build-arg ARCH --build-arg KUBERNETES_RELEASE -f ./package/Dockerfile.kubectl .
echo ${IMAGE} >> ./dist/images
echo Built ${IMAGE}
