#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ "$ARCH" != "arm" ]; then
    export DOCKER_BUILDKIT=1
fi

docker build \
  --build-arg ARCH=${ARCH} \
  --build-arg REPO=${REPO} \
  --build-arg TAG=${TAG} \
  --build-arg VERSION=${VERSION} \
  --file package/Dockerfile \
  --tag ${REPO}/system-upgrade-controller:${TAG} \
  --tag ${REPO}/system-upgrade-controller:latest \
.
docker image save --output ./dist/images.tar \
  ${REPO}/system-upgrade-controller:${TAG} \
  ${REPO}/system-upgrade-controller:latest
echo ${REPO}/system-upgrade-controller:${TAG} > ./dist/images.txt
echo Built ${REPO}/system-upgrade-controller:${TAG}
