name: Release

# The jobs below will execute any time a tag is pushed to any branch in the repo.
on:
  push:
    tags:
      - '*'

env:
  IMAGE: rancher/system-upgrade-controller
  TAG: ${{ github.ref_name }}

jobs:
  # Runs build, test, package, and e2e checks and uploads the generated artifacts to
  # GitHub Actions so we can reference them when we create the GitHub release.
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64, arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Install CI tools
        run: bash ./scripts/install-ci-tools

      - name: Run CI
        run: make ci ARCH=${{ matrix.arch }}
      
      - name: Run e2e
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          make e2e-sonobuoy ARCH=${{ matrix.arch }}
          make e2e-verify ARCH=${{ matrix.arch }}

      - name: Generate artifact checksums
        run: find dist/artifacts -type f -exec sha256sum {} \; > "dist/artifacts/sha256sum-${{ matrix.arch }}.txt"

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "artifacts-${{ matrix.os }}-${{ matrix.arch }}"
          path: dist/artifacts/*
          if-no-files-found: error
          overwrite: true

  # Creates a GitHub release using artifacts from the `build-test` job.
  create-gh-release:
    runs-on: ubuntu-latest
    needs: 
      - build-test
      - publish
    permissions:
      contents: write # needed for creating the GH release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Fix the not-a-git-repository issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          path: dist/artifacts
          pattern: artifacts-*
          merge-multiple: true

      - name: Create GitHub release
        run: gh release create "${{ env.TAG }}" --prerelease --title "${{ env.TAG }}" dist/artifacts/* ||
             gh release upload "${{ env.TAG }}" --clobber dist/artifacts/*

  # Publishes signed Docker images built from source using Docker buildx.
  publish:
    runs-on: ubuntu-latest
    needs: 
      - build-test
    permissions:
      contents: read
      id-token: write # required for Vault auth and cosign signing
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Fix the not-a-git-repository issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Read secrets
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry | PRIME_STG_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username | PRIME_STG_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password | PRIME_STG_REGISTRY_PASSWORD

      - name: Publish image
        uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # v0.65.2
        with:
          image: system-upgrade-controller
          tag: ${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm

          public-registry: docker.io
          public-repo: rancher
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}

          identity-registry: ${{ env.PRIME_REGISTRY }}
          prime-registry: ${{ env.PRIME_STG_REGISTRY }}
          prime-repo: rancher
          prime-make-target: push-prime-image
          prime-username: ${{ env.PRIME_STG_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_STG_REGISTRY_PASSWORD }}
